/* -*- mode: c++; indent-tabs-mode: nil -*- */
#ifndef _QORE_NCURSES_INTERNAL_H
#define _QORE_NCURSES_INTERNAL_H

#include <qore/Qore.h>
#include <qore/QoreSandboxManager.h>

#include <map>
#include <utility>
#include <vector>

#include <stdlib.h>

#include <ncurses.h>
#include <panel.h>

#if defined(__linux__)
#include <pty.h>
#include <sys/ioctl.h>
#include <unistd.h>
#elif defined(__APPLE__) || defined(__FreeBSD__) || defined(__NetBSD__) || defined(__OpenBSD__)
#include <util.h>
#include <sys/ioctl.h>
#include <unistd.h>
#endif

extern QoreRecursiveThreadLock ncurses_lock;

// Qore class IDs and class pointers generated by QPP
extern qore_classid_t CID_SESSION;
extern qore_classid_t CID_WINDOW;
extern qore_classid_t CID_PANEL;
extern qore_classid_t CID_TESTTERMINAL;

extern QoreClass* QC_SESSION;
extern QoreClass* QC_WINDOW;
extern QoreClass* QC_PANEL;
extern QoreClass* QC_TESTTERMINAL;

// Input event type values (keep in sync with Qore::Ncurses::InputType enum)
constexpr int NC_INPUT_NONE = 0;
constexpr int NC_INPUT_CHAR = 1;
constexpr int NC_INPUT_KEY = 2;
constexpr int NC_INPUT_MOUSE = 3;
constexpr int NC_INPUT_RESIZE = 4;
constexpr int NC_INPUT_ALT = 5;

struct StyleSpec {
    bool has_fg = false;
    bool has_bg = false;
    int fg = -1;
    int bg = -1;
    int attrs = 0;
};

struct AnsiSegment {
    std::string text;
    StyleSpec style;
};

class NcursesSession : public AbstractPrivateData {
public:
    SCREEN* screen = nullptr;
    WINDOW* stdwin = nullptr;
    bool is_default = false;
    bool closed = false;
    bool colors_enabled = false;
    bool use_default_colors = false;
    short next_pair = 1;
    std::map<std::pair<int, int>, short> pair_cache;
    WINDOW* cursor_win = nullptr;
    int cursor_y = 0;
    int cursor_x = 0;
    bool cursor_set = false;

    FILE* in_file = nullptr;
    FILE* out_file = nullptr;

    NcursesSession();
    ~NcursesSession();

    void close(ExceptionSink* xsink);
    void checkOpen(ExceptionSink* xsink) const;
    short getColorPair(int fg, int bg, ExceptionSink* xsink);
};

class NcursesWindow : public AbstractPrivateData {
public:
    NcursesSession* session = nullptr;
    WINDOW* win = nullptr;
    bool owned = false;
    bool leave_ok = false;
    int wrap_mode = 1;

    NcursesWindow(NcursesSession* s, WINDOW* w, bool own);
    ~NcursesWindow();

    void checkOpen(ExceptionSink* xsink) const;
};

class NcursesPanel : public AbstractPrivateData {
public:
    NcursesSession* session = nullptr;
    PANEL* panel = nullptr;
    QoreObject* window_obj = nullptr;

    NcursesPanel(NcursesSession* s, PANEL* p, QoreObject* wobj);
    ~NcursesPanel();

    void checkOpen(ExceptionSink* xsink) const;
};

class NcursesTestTerminal : public AbstractPrivateData {
public:
    int master_fd = -1;
    int slave_fd = -1;
    int rows = 24;
    int cols = 80;
    QoreString term;

    NcursesTestTerminal(int r, int c, const QoreString* t);
    ~NcursesTestTerminal();

    void open(ExceptionSink* xsink);
    void close(ExceptionSink* xsink);
    void resize(int r, int c, ExceptionSink* xsink);
    void writeInput(const QoreString* data, ExceptionSink* xsink);
    void ensureOpen(ExceptionSink* xsink);
};

class NcursesCallGuard {
public:
    AutoLocker lock;
    SCREEN* prev = nullptr;

    NcursesCallGuard(NcursesSession* s);
    ~NcursesCallGuard();
};

bool parseStyle(const QoreHashNode* h, StyleSpec& out, ExceptionSink* xsink);
void applyStyle(NcursesWindow* w, const StyleSpec& style, attr_t& old_attr, short& old_pair, ExceptionSink* xsink);
void restoreStyle(NcursesWindow* w, attr_t old_attr, short old_pair);
void parseAnsiSegments(const QoreString* text, std::vector<AnsiSegment>& segs);
void drawAnsiText(NcursesWindow* w, int y, int x, bool inside, bool clear_line, const QoreString* text,
    ExceptionSink* xsink);

extern const TypedHashDecl* hashdeclStyle;
extern const TypedHashDecl* hashdeclSize;
extern const TypedHashDecl* hashdeclPosition;
extern const TypedHashDecl* hashdeclMouseEvent;
extern const TypedHashDecl* hashdeclInputEvent;
extern QoreEnumDecl* enumWrapMode;

#endif
